language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  api_key:
    secure: CBOl0zDRz5O06Q1dBENxoqPVHTgXJbqpWYIpOXGBq5xXwWKVE2n0aCkxaeH6OIudsABYaGvBxj6ApDu8SYxgfDAD9Uo1GI41tkYGB7pNcwizI+K0ayukk9d85A1lYcLLxDKvvDdMKJ+TOQdPNwqzaEhUNKY7+Yvh4LjBg03SDGqT8yqeEKlhngNHbPewYq2352ovAl2nHBjt3n7SpPwk1pOgl/dG9zEnXfIi5ZnWBVPbfnaBhvwjcPhkQInNMUMFbWKE6KkuA+1lBRul87PVxvY/QC/lG3QHOXw3m2IPDU/7i4qiV25pdZar4QzMkSBgSjVgP8UYs290LjwhhYGq+umu3Dsr7AwkjcAjhpUVd+C5A57/42honfs4gwtHa+r+BagzgFhRrSDSe/+f0KtNaVZHegUV4m8yRN9HsdfHHsPB1HnwOiiqrai4wBvIGqauep3MICNF90TempvzAT5pKTlhBn6ystccZz0gxxmGqV0/R9e3zTyvbERVGFiRJw68+pDS8vwX45Qhr4DoRWksW6A6Ia9elR6VuyYAgvT+em1bze1lkl1B2xEBhFQz88xXTLVR2kMGCcGTxw//6EMdjoA1bcMJtiwiItRiLQaiu2tgEIVo8Gtf8p3Y8eHpFBxxNoo1HILWm4kvjMIZ59ZlDld2y5qO//xhhwLEuiYrz5c=
